In [23]:
import numpy as np

### Load

In [33]:
x = np.loadtxt('Problem4.6.txt')
x

array([ 10.,  13.,   8.,  15.,   8.,  13.,  14.,  13.,  19.,   8.,  13.,
        13.,   7.,   8.,   6.,   8.,  11.,  12.,   8.,   7.])

### Mean

In [34]:
xbest = sum(x)/len(x)
xbest

10.699999999999999

### Deviation

In [35]:
deviation = np.array([(entry - xbest) for entry in x])
deviation

array([-0.7,  2.3, -2.7,  4.3, -2.7,  2.3,  3.3,  2.3,  8.3, -2.7,  2.3,
        2.3, -3.7, -2.7, -4.7, -2.7,  0.3,  1.3, -2.7, -3.7])

### Squared Deviation

In [36]:
deviation2 = np.array([(entry-xbest)**2 for entry in x])
deviation2

array([  0.49,   5.29,   7.29,  18.49,   7.29,   5.29,  10.89,   5.29,
        68.89,   7.29,   5.29,   5.29,  13.69,   7.29,  22.09,   7.29,
         0.09,   1.69,   7.29,  13.69])

### Standard Deviation

In [37]:
std = np.sqrt((1/(len(x)-1))*np.sum(deviation2))
std

3.404331606088121

### Deviation of the Mean

In [38]:
stdotm = std/np.sqrt(len(x))
stdotm

0.76123168891640747

### Built-in Results

In [39]:
xmean = np.mean(x)
xmean

10.699999999999999

In [40]:
xstd = np.std(x,ddof=1)
xstd

3.404331606088121

Numpy's calculations agree with the results above.